package com.vivance.gtw.dao.Package;

public enum StatusEnum {
    BOOKING_INPROGRESS,
    BOOKING_CONFIRMED,
    BOOKING_HOLD,
    BOOKING_CANCELLED,
    BOOKING_ERROR,
    BOOKING_INCOMPLETE,
    BOOKING_VOUCHERED,
    BOOKING_PENDING,
    BOOKING_FAILED;
}
